### ISSUE TITLE
Refresh Page after swap

### ISSUE THREAD

**Issue by PavlovsBigBell** [wynddaoOld/dex-issue-tracker#15] opened 2022-12-27 12:35 UTC
When I swapped to, the new balances did not appear when I went to deposit liquidity into a pool.  I needed to manually refresh the page. 

Should fix where the page automatically refreshes after swapping to give balances updated.

**Comment by PavlovsBigBell** [comment] 2022-12-27 12:38
Also, after claiming unbonded tokens the available LP balance did not refresh.  This should also auto-refresh

**Comment by WYNerD** [comment] 2022-12-27 14:35
Duplicate of #21. Let's merge this.

**Closed as completed by WYNerD** 2022-12-27 14:35 UTC
