### ISSUE TITLE
Cant trade

### ISSUE THREAD

**Issue by stephen94k** [wynddaoOld/dex-issue-tracker#8] opened 2022-12-25 01:08 UTC
I am on test net and I try to do a trade.

The keplr gas window pops up and I selected a gas and proceed, it says error something went wrong.

No TX gets to my ledger to sign

**Comment by WYNerD** [comment] 2022-12-25 09:46
Can you open your console (F12) and try to do a trade? Then Screenshot the result.

**Comment by PavlovsBigBell** [comment] 2022-12-25 19:09
It seems like the issue is with Ledgers and hardware wallets.  He deleted the same stuff you told me on F12 screen and changed the RPC and LCD endpoints.

**Comment by WYNerD** [comment] 2022-12-25 21:19
Let's do this in a call next week. Hard to debug without seeing the issue

**Comment by stephen94k** [comment] 2022-12-27 00:05
I tried it with a soft wallet and a ledger.

The soft wallet worked with no issues, but as soon as I switch it to use Ledger it does not send any TX for the Ledger and errors out.

**Comment by WYNerD** [comment] 2022-12-27 09:30
Was a issue by the wallet provider we use (cosmology / cosmos-kit) . They fixed it with https://github.com/cosmology-tech/cosmos-kit/commit/dcd6de05199ec8c7ef3a0bf47aa3f1738ef7f87c , updated and working!

**Comment by WYNerD** [comment] 2022-12-27 09:30
Please confirm, so we can close this issue

**Closed as completed** 2022-12-27 09:47 UTC
Labels: bug, waiting for review
