### ISSUE TITLE
[High Priority] [UX] Rebonding Period allow to decreased the period (re-rebond) on front-end (fail on back-end as expected)

### ISSUE THREAD

**Issue by apollo-pablo** [wynddaoOld/dex-issue-tracker#28] opened 2022-12-27 17:59 UTC
> Problem

When a user has already an LP bonded for 4 days, after he decreases to 3 days for example, later the system offer this 3 days unbonding period to reduce to 2 days even more which is not expected until 3/xxx days passes?

![image](https://user-images.githubusercontent.com/95628259/209704526-aed8d259-8f3b-4adf-a944-03c7d47107dd.png)

**Comment by WYNerD** [comment] 2022-12-27 20:20
Duplicate of #24. Closed 24. 

Same problem, when only a portion of it is unavailable. Need to keep unavailable tokens in mind.

**Closed as completed** 2023-01-16 09:44 UTC
Labels: bug
